name: "Zoul Test Experiment"
experimentId: "1234567890"
nodes:
  - id: raspi01
    modules:
      - id: ZOUL
        firmware: "zoul-test.zoul"
  - id: raspi02
    modules:
      - id: ZOUL
        firmware: "zoul-test.zoul"