# This is what a configuration for the server might look like

workingDirectory: "datastore"

server:
  requestLog:
    appenders: []

logging:
  level: OFF
  loggers:
    "de.cau.testbed.server": INFO
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: "datastore/logs/server.log"
      archivedLogFilenamePattern: "datastore/logs/server.%d.log.gz"
      archivedFileCount: 5
    - type: console
      threshold: INFO
      target: stdout

kafkaAddress: localhost:9092
numFirmwareDistributionThreads: 10
numLogRetrievalThreads: 10
heartbeatInterval: 10_000 # Milliseconds
nodes:
  - id: raspi01
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi02
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi03
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi04
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi06
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi07
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi08
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi09
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi10
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi12
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi13
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi14
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi15
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi16
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi17
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi18
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi19
    capabilities: [ ZOUL, SKY, NRF52 ]
  - id: raspi21
    capabilities: [ ZOUL, SKY, NRF52 ]