name: "Zoul Test Experiment"
experimentId: "1234567890"
start: "2022-06-29T14:57:00"
end: "2022-06-29T14:57:10"
nodes:
  - id: raspi01
    modules:
      - id: ZOUL
        firmware: "zoul-test.zoul"
      - id: SKY
        firmware: "sky.hex"
  - id: raspi02
    modules:
      - id: ZOUL
        firmware: "zoul-test.zoul"